services:
  telegram-auth:
    build:
      context: ../..
      dockerfile: docker/app/Dockerfile
      target: telegram-auth
    container_name: telegram_auth_app
    env_file:
      - .env.telegram_auth.docker
    command: python -m uvicorn telegram_agent.core.telegram_auth.api.v1.fastapi_app:fastapi_app --host 0.0.0.0 --port 8000
    volumes:
      - ../..:/app
    networks:
      - fatol-net
  telegram-ingress:
    build:
      context: ../..
      dockerfile: docker/app/Dockerfile
      target: telegram-ingress
    container_name: telegram_ingress_app
    env_file:
      - .env.telegram_ingress.docker
    command: python -m uvicorn telegram_agent.core.telegram_ingress.api.v1.fastapi_app:fastapi_app --host 0.0.0.0 --port 8000
    volumes:
      - ../..:/app
    networks:
      - fatol-net
  content-processing:
    build:
      context: ../..
      dockerfile: docker/app/Dockerfile
      target: content-processing
    container_name: content_processing_app
    env_file:
      - .env.content_processing.docker
    command: python -m uvicorn telegram_agent.core.content_processing.api.v1.fastapi_app:fastapi_app --host 0.0.0.0 --port 8000
    volumes:
      - ../..:/app
    networks:
      - fatol-net
  agent-runtime:
    build:
      context: ../..
      dockerfile: docker/app/Dockerfile
      target: agent-runtime
    container_name: agent_runtime_app
    env_file:
      - .env.agent_runtime.docker
    command: python -m uvicorn telegram_agent.core.agent_runtime.api.v1.fastapi_app:fastapi_app --host 0.0.0.0 --port 8000
    volumes:
      - ../..:/app
    networks:
      - fatol-net
networks:
  fatol-net:
