services:
  whisperx:
    build:
      context: ../..
      dockerfile: docker/app/Dockerfile
      target: whisperx
    env_file:
      - .env.whisperx.docker
    container_name: whisperx_service
    runtime: nvidia
    volumes:
      - ../../.cache/huggingface:/root/.cache/huggingface
      - ../..:/app
    ipc: host
    command: >
      python -m uvicorn telegram_agent.core.whisperx.api.v1.fastapi_app:fastapi_app
      --host 0.0.0.0
      --port 8000
    networks:
      - fatol-net

networks:
  fatol-net:
