"""Default (non-secret) configuration values used by BaseSettings."""
from __future__ import annotations

from zoneinfo import ZoneInfo

DEFAULT_SQLALCHEMY_DATABASE_URL = "postgresql+asyncpg://postgres:postgres@localhost:5432/telegram_agent"
DEFAULT_ALLOWED_ORIGINS = (
    "http://localhost:5678,"
    "https://ops.fatolai.com,"
)
DEFAULT_TELEGRAM_AUTH_BASE_URL="http://localhost:8000/api/v1/telegram-auth"
DEFAULT_REDIS_URL = "redis://localhost:6379/0"
DEFAULT_TELEGRAM_API_BASE_URL = "https://api.telegram.org"
DEFAULT_MEDIA_STORAGE_ROOT = "/app/media"
DEFAULT_WHISPERX_BASE_URL = "http://localhost:8000/api/v1"
DEFAULT_CHUNKING_BASE_URL = "http://localhost:8000/api/v1"
DEFAULT_CHUNKING_REQUEST_TIMEOUT_SECONDS = 60.0
DEFAULT_MEDIA_DOWNLOAD_MAX_BYTES = 2 * 1024 * 1024 * 1024
DEFAULT_MEDIA_DOWNLOAD_CHUNK_SIZE = 1024 * 1024
DEFAULT_MEDIA_HTTP_CONNECT_TIMEOUT_SECONDS = 10.0
DEFAULT_MEDIA_HTTP_READ_TIMEOUT_SECONDS = 60.0
DEFAULT_MEDIA_HTTP_WRITE_TIMEOUT_SECONDS = 60.0
DEFAULT_MEDIA_HTTP_POOL_TIMEOUT_SECONDS = 10.0
DEFAULT_MEDIA_PROCESSING_LEASE_SECONDS = 900
DEFAULT_MEDIA_TASK_MAX_RETRIES = 5
DEFAULT_MEDIA_TASK_RETRY_BASE_SECONDS = 5
DEFAULT_FFMPEG_BINARY = "ffmpeg"
DEFAULT_FFMPEG_TIMEOUT_SECONDS = 600.0
DEFAULT_WHISPERX_MODEL = "large-v3"
DEFAULT_WHISPERX_REQUEST_TIMEOUT_SECONDS = 600.0
DEFAULT_OUTBOX_DISPATCH_BATCH_SIZE = 50
DEFAULT_OUTBOX_DISPATCH_POLL_INTERVAL_SECONDS = 5.0
DEFAULT_OUTBOX_DISPATCH_LEASE_SECONDS = 60
DEFAULT_OUTBOX_RETRY_BASE_SECONDS = 5
DEFAULT_OUTBOX_RETRY_MAX_SECONDS = 300
DEFAULT_LOG_LEVEL = "DEBUG"
DEFAULT_TELEGRAM_INGRESS_BASE_URL = "http://localhost:8000/api/v1/telegram"
DEFAULT_TELEGRAM_INGRESS_REQUEST_TIMEOUT_SECONDS = 10.0
DEFAULT_CALLBACK_TASK_MAX_RETRIES = 5
DEFAULT_CALLBACK_TASK_RETRY_BASE_SECONDS = 5
DEFAULT_JOB_EXPECTATION_VOICE_VIDEO_NOTE_SECONDS = 30
DEFAULT_JOB_EXPECTATION_DEFAULT_SECONDS = 60
DEFAULT_JOB_EXPECTATION_SWEEP_INTERVAL_SECONDS = 30.0
DEFAULT_JOB_EXPECTATION_SWEEP_BATCH_SIZE = 50
DEFAULT_JOB_EXPECTATION_SWEEP_LEASE_SECONDS = 60
DEFAULT_JOB_EXPECTATION_RESOLVED_RETENTION_SECONDS = 0
DEFAULT_LLM_GATEWAY_BASE_URL = "http://localhost:8000/v1"
DEFAULT_LLM_GATEWAY_REQUEST_TIMEOUT_SECONDS = 120.0
DEFAULT_SUBTITLE_TRANSLATION_ENABLED = True
DEFAULT_SUBTITLE_TRANSLATION_MAX_SOURCE_TOKENS = 3000
DEFAULT_SUBTITLE_TRANSLATION_MAX_SEGMENTS_PER_BATCH = 18
DEFAULT_SUBTITLE_TRANSLATION_PREVIOUS_CONTEXT = 5
DEFAULT_SUBTITLE_TRANSLATION_LOOKAHEAD = 3
DEFAULT_SUBTITLE_GLOSSARY_MAX_WINDOWS = 3
DEFAULT_SUBTITLE_GLOSSARY_MAX_WINDOWS_LONG = 8
DEFAULT_SUBTITLE_GLOSSARY_WINDOW_TOKEN_BUDGET = 6000
DEFAULT_SUBTITLE_GLOSSARY_OVERLAP_RATIO = 0.12
DEFAULT_SUBTITLE_GLOSSARY_MAX_ENTRIES = 200
DEFAULT_SUBTITLE_TRANSLATION_BATCH_LEASE_SECONDS = 300
DEFAULT_SUBTITLE_TRANSLATION_MAX_BATCH_ATTEMPTS = 5
