"""Default (non-secret) configuration values used by BaseSettings."""
from __future__ import annotations

from zoneinfo import ZoneInfo

DEFAULT_SQLALCHEMY_DATABASE_URL = "postgresql+asyncpg://postgres:postgres@localhost:5432/telegram_agent"
DEFAULT_ALLOWED_ORIGINS = (
    "http://localhost:5678,"
    "https://ops.fatolai.com,"
)
DEFAULT_TELEGRAM_AUTH_BASE_URL="http://localhost:8000/api/v1/telegram-auth"
DEFAULT_REDIS_URL = "redis://localhost:6379/0"
DEFAULT_TELEGRAM_API_BASE_URL = "https://api.telegram.org"
DEFAULT_MEDIA_STORAGE_ROOT = "/app/media"
DEFAULT_WHISPERX_BASE_URL = "http://localhost:8000/api/v1"
DEFAULT_MEDIA_DOWNLOAD_MAX_BYTES = 2 * 1024 * 1024 * 1024
DEFAULT_MEDIA_DOWNLOAD_CHUNK_SIZE = 1024 * 1024
DEFAULT_MEDIA_HTTP_CONNECT_TIMEOUT_SECONDS = 10.0
DEFAULT_MEDIA_HTTP_READ_TIMEOUT_SECONDS = 60.0
DEFAULT_MEDIA_HTTP_WRITE_TIMEOUT_SECONDS = 60.0
DEFAULT_MEDIA_HTTP_POOL_TIMEOUT_SECONDS = 10.0
DEFAULT_MEDIA_PROCESSING_LEASE_SECONDS = 900
DEFAULT_MEDIA_TASK_MAX_RETRIES = 5
DEFAULT_MEDIA_TASK_RETRY_BASE_SECONDS = 5
DEFAULT_FFMPEG_BINARY = "ffmpeg"
DEFAULT_FFMPEG_TIMEOUT_SECONDS = 600.0
DEFAULT_WHISPERX_MODEL = "large-v3"
DEFAULT_WHISPERX_REQUEST_TIMEOUT_SECONDS = 600.0
DEFAULT_OUTBOX_DISPATCH_BATCH_SIZE = 50
DEFAULT_OUTBOX_DISPATCH_POLL_INTERVAL_SECONDS = 5.0
DEFAULT_OUTBOX_DISPATCH_LEASE_SECONDS = 60
DEFAULT_OUTBOX_RETRY_BASE_SECONDS = 5
DEFAULT_OUTBOX_RETRY_MAX_SECONDS = 300
DEFAULT_LOG_LEVEL = "DEBUG"
DEFAULT_TELEGRAM_INGRESS_BASE_URL = "http://localhost:8000/api/v1/telegram"
DEFAULT_TELEGRAM_INGRESS_REQUEST_TIMEOUT_SECONDS = 10.0
DEFAULT_CALLBACK_TASK_MAX_RETRIES = 5
DEFAULT_CALLBACK_TASK_RETRY_BASE_SECONDS = 5
