from telegram_agent.core.common.db.session_factory import create_sync_session_factory
from telegram_agent.core.telegram_auth.common.settings import settings

SyncSessionLocal = create_sync_session_factory(settings.sqlalchemy_database_url)