"""Default (non-secret) configuration values used by BaseSettings."""
from __future__ import annotations

from zoneinfo import ZoneInfo

DEFAULT_WHISPERX_MODEL = "large-v3"
DEFAULT_WHISPERX_MERGE_SAME_SPEAKER_ONLY = True
DEFAULT_WHISPERX_SEGMENT_TARGET_DURATION_SECONDS = 7.0
DEFAULT_WHISPERX_SEGMENT_MIN_DURATION_SECONDS = 2.0
DEFAULT_WHISPERX_SEGMENT_MAX_DURATION_SECONDS = 11.0
DEFAULT_WHISPERX_SEGMENT_TARGET_WORD_COUNT = 24
DEFAULT_WHISPERX_SEGMENT_MIN_WORD_COUNT = 7
DEFAULT_WHISPERX_SEGMENT_MAX_WORD_COUNT = 34
DEFAULT_WHISPERX_SEGMENT_PAUSE_SECONDS = 0.5