"""create user message

Revision ID: e2e9224a2f4c
Revises: 
Create Date: 2026-07-07 05:40:36.130410

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e2e9224a2f4c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_messages',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('telegram_user_id', sa.BigInteger(), nullable=False),
                    sa.Column('chat_id', sa.BigInteger(), nullable=False),
                    sa.Column('message_id', sa.BigInteger(), nullable=False),
                    sa.Column('update_id', sa.BigInteger(), nullable=True),
                    sa.Column('reply_message_id', sa.BigInteger(), nullable=True),
                    sa.Column('text', sa.Text(), nullable=True),
                    sa.Column('conversation_status', sa.String(length=32), server_default='pending', nullable=False),
                    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'),
                              nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('chat_id', 'message_id', name='uq_user_messages_chat_id_message_id'),
                    sa.UniqueConstraint("update_id", name="uq_user_messages_update_id", ),
                    )
    op.create_index(op.f('ix_user_messages_chat_id'), 'user_messages', ['chat_id'], unique=False)
    op.create_index(op.f('ix_user_messages_telegram_user_id'), 'user_messages', ['telegram_user_id'], unique=False)
    op.create_index(
        "ix_user_messages_recent",
        "user_messages",
        [sa.text("created_at DESC"), sa.text("id DESC")],
        unique=False,
    )
    op.create_table('attachments',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('user_message_id', sa.UUID(), nullable=False),
                    sa.Column('file_id', sa.String(length=512), nullable=False),
                    sa.Column('file_unique_id', sa.String(length=255), nullable=True),
                    sa.Column("type", sa.String(length=32), nullable=False),
                    sa.Column("status", sa.String(length=32), server_default="pending", nullable=False),
                    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'),
                              nullable=False),
                    sa.ForeignKeyConstraint(['user_message_id'], ['user_messages.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_attachments_file_unique_id'), 'attachments', ['file_unique_id'], unique=False)
    op.create_index(op.f('ix_attachments_user_message_id'), 'attachments', ['user_message_id'], unique=True)
    op.create_table(
        "conversation_outbox_events",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("event_type", sa.String(length=128), nullable=False),
        sa.Column("chat_id", sa.BigInteger(), nullable=False),
        sa.Column("first_message_id", sa.BigInteger(), nullable=False),
        sa.Column("idempotency_key", sa.String(length=255), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sa.String(length=32), server_default="pending", nullable=False),
        sa.Column("attempt_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("available_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("locked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("locked_by", sa.String(length=255), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "attempt_count >= 0",
            name="ck_conversation_outbox_events_attempt_count_non_negative",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "idempotency_key",
            name="uq_conversation_outbox_events_idempotency_key",
        ),
    )
    op.create_index(
        op.f("ix_conversation_outbox_events_chat_id"),
        "conversation_outbox_events",
        ["chat_id"],
        unique=False,
    )
    op.create_index(
        "ix_conversation_outbox_events_pending_available",
        "conversation_outbox_events",
        ["available_at", "created_at"],
        unique=False,
        postgresql_where=sa.text("status = 'pending'"),
    )
    op.create_index(
        "ix_conversation_outbox_events_processing_lease",
        "conversation_outbox_events",
        ["locked_at"],
        unique=False,
        postgresql_where=sa.text("status = 'processing'"),
    )

    op.add_column(
        "user_messages",
        sa.Column("dispatch_event_id", sa.UUID(), nullable=True),
    )
    op.create_foreign_key(
        "fk_user_messages_dispatch_event_id",
        "user_messages",
        "conversation_outbox_events",
        ["dispatch_event_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_index(
        op.f("ix_user_messages_dispatch_event_id"),
        "user_messages",
        ["dispatch_event_id"],
        unique=False,
    )
    op.create_index(
        "ix_user_messages_chat_pending_order",
        "user_messages",
        ["chat_id", "message_id"],
        unique=False,
        postgresql_where=sa.text("conversation_status = 'pending'"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_attachments_user_message_id'), table_name='attachments')
    op.drop_index(op.f('ix_attachments_file_unique_id'), table_name='attachments')
    op.drop_table('attachments')
    op.drop_index("ix_user_messages_recent", table_name="user_messages")
    op.drop_index(op.f('ix_user_messages_telegram_user_id'), table_name='user_messages')
    op.drop_index(op.f('ix_user_messages_chat_id'), table_name='user_messages')
    op.drop_table('user_messages')
    op.drop_index("ix_user_messages_chat_pending_order", table_name="user_messages")
    op.drop_index(op.f("ix_user_messages_dispatch_event_id"), table_name="user_messages")
    op.drop_constraint(
        "fk_user_messages_dispatch_event_id",
        "user_messages",
        type_="foreignkey",
    )
    op.drop_column("user_messages", "dispatch_event_id")
    op.drop_index(
        "ix_conversation_outbox_events_processing_lease",
        table_name="conversation_outbox_events",
    )
    op.drop_index(
        "ix_conversation_outbox_events_pending_available",
        table_name="conversation_outbox_events",
    )
    op.drop_index(
        op.f("ix_conversation_outbox_events_chat_id"),
        table_name="conversation_outbox_events",
    )
    op.drop_table("conversation_outbox_events")
    # ### end Alembic commands ###
