"""create user message

Revision ID: e2e9224a2f4c
Revises: 
Create Date: 2026-07-07 05:40:36.130410

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2e9224a2f4c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('telegram_user_id', sa.BigInteger(), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('message_id', sa.BigInteger(), nullable=False),
    sa.Column('update_id', sa.BigInteger(), nullable=True),
    sa.Column('reply_message_id', sa.BigInteger(), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('conversation_status', sa.String(length=32), server_default='pending', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chat_id', 'message_id', name='uq_user_messages_chat_id_message_id'),
    sa.UniqueConstraint("update_id",name="uq_user_messages_update_id",),
    )
    op.create_index(op.f('ix_user_messages_chat_id'), 'user_messages', ['chat_id'], unique=False)
    op.create_index(op.f('ix_user_messages_telegram_user_id'), 'user_messages', ['telegram_user_id'], unique=False)
    op.create_table('attachments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_message_id', sa.UUID(), nullable=False),
    sa.Column('file_id', sa.String(length=512), nullable=False),
    sa.Column('file_unique_id', sa.String(length=255), nullable=True),
    sa.Column("type", sa.String(length=32), nullable=False),
    sa.Column("status", sa.String(length=32), server_default="pending", nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_message_id'], ['user_messages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attachments_file_unique_id'), 'attachments', ['file_unique_id'], unique=False)
    op.create_index(op.f('ix_attachments_user_message_id'), 'attachments', ['user_message_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_attachments_user_message_id'), table_name='attachments')
    op.drop_index(op.f('ix_attachments_file_unique_id'), table_name='attachments')
    op.drop_table('attachments')
    op.drop_index(op.f('ix_user_messages_telegram_user_id'), table_name='user_messages')
    op.drop_index(op.f('ix_user_messages_chat_id'), table_name='user_messages')
    op.drop_table('user_messages')
    # ### end Alembic commands ###
