from __future__ import annotations


DEFAULT_REPLY_MODEL = "gpt-5.4"
DEFAULT_REPLY_TEMPERATURE = 0.2
DEFAULT_OPENAI_REQUEST_TIMEOUT_SECONDS = 30.0
DEFAULT_OPENAI_CONNECT_TIMEOUT_SECONDS = 5.0
DEFAULT_OPENAI_MAX_RETRIES = 2

