from __future__ import annotations


DEFAULT_REPLY_MODEL = "gpt-5.4"
DEFAULT_REPLY_TEMPERATURE = 0.2
DEFAULT_OPENAI_REQUEST_TIMEOUT_SECONDS = 30.0
DEFAULT_OPENAI_CONNECT_TIMEOUT_SECONDS = 5.0
DEFAULT_OPENAI_MAX_RETRIES = 2
DEFAULT_DOWNLOAD_AGENT_BACKEND = "openai"
DEFAULT_DOWNLOAD_AGENT_LOCAL_MODEL = "Qwen/Qwen3-4B-Instruct-2507"
DEFAULT_DOWNLOAD_AGENT_LOCAL_MAX_VALIDATION_ATTEMPTS = 3
DEFAULT_DOWNLOAD_AGENT_LOCAL_MAX_NEW_TOKENS = 512
DEFAULT_DOWNLOAD_AGENT_LOCAL_JOB_TIMEOUT_SECONDS = 180
DEFAULT_DOWNLOAD_AGENT_LOCAL_JOB_MAX_ATTEMPTS = 2
DEFAULT_GPU_EXECUTION_BASE_URL = "http://gpu-execution:8000/api/v1"
DEFAULT_GPU_SHARED_STORAGE_ROOT = "/app/media"
DEFAULT_GPU_EXECUTION_HTTP_TIMEOUT_SECONDS = 10.0
DEFAULT_GPU_EXECUTION_POLL_INTERVAL_SECONDS = 1.0
DEFAULT_GPU_EXECUTION_WAIT_TIMEOUT_SECONDS = 300.0

